### PR TITLE
Cleanup & update to 6.0 v111

### PR DESCRIPTION
**Pull request by skykatik**
The plugin is very good but it`s outdated

### CODE REVIEW

**Comment by skykatik** [comment]
_Okay. Everything is exactly there are shortcomings_

**Comment by mayli** [comment]
? why closed?

**Comment by skykatik** [comment]
I'll open it later, there's something to improve

**Comment by mayli** [comment]
@skykatik I've posted a new release, 
https://github.com/mayli/RockTheVotePlugin/releases/download/v112.1/RockTheVotePlugin.jar
let me know if it's working for you.

**Pull request closed without merging**
